// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Layout");

function make(children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("html", undefined, React.createElement("head", undefined, React.createElement("meta", {
                                  content: "width=device-width, initial-scale=1.0",
                                  name: "viewport"
                                })), React.createElement("body", undefined, React.createElement("div", {
                                  className: "mdl-layout mdl-js-layout mdl-layout--fixed-header"
                                }, React.createElement("header", {
                                      className: "mdl-layout__header"
                                    }, React.createElement("div", {
                                          className: "mdl-layout__header-row"
                                        }, React.createElement("span", {
                                              className: "mdl-layout-title"
                                            }, "NameTags"), React.createElement("div", {
                                              className: "mdl-layout-spacer"
                                            }), React.createElement("nav", {
                                              className: "mdl-navigation mdl-layout--large-screen-only"
                                            }, React.createElement("a", {
                                                  className: "mdl-navigation__link",
                                                  href: "/"
                                                }, "Frontpage"), React.createElement("a", {
                                                  className: "mdl-navigation__link",
                                                  href: "/config"
                                                }, "Config")))), React.createElement("div", {
                                      className: "mdl-layout__drawer"
                                    }, React.createElement("span", {
                                          className: "mdl-layout-title"
                                        }, "Title"), React.createElement("nav", {
                                          className: "mdl-navigation"
                                        }, React.createElement("a", {
                                              className: "mdl-navigation__link",
                                              href: "/"
                                            }, "Frontpage"), React.createElement("a", {
                                              className: "mdl-navigation__link",
                                              href: "/config"
                                            }, "Config"))), React.createElement("main", {
                                      className: "mdl-layout__content mdl-color--grey-100"
                                    }, React.createElement("div", {
                                          className: "page-content",
                                          style: {
                                            padding: "8px"
                                          }
                                        }, ReactDOMRe.createElementVariadic("div", {
                                              style: {
                                                padding: "20px"
                                              }
                                            }, children)))), React.createElement("link", {
                                  href: "https://fonts.googleapis.com/icon?family=Material+Icons",
                                  rel: "stylesheet"
                                }), React.createElement("link", {
                                  href: "https://code.getmdl.io/1.3.0/material.blue-pink.min.css",
                                  rel: "stylesheet"
                                }), React.createElement("script", {
                                  src: "https://code.getmdl.io/1.3.0/material.min.js"
                                })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
