// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Students = require("./students");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Server = require("react-dom/server");

function classes(json) {
  return /* record */[
          /* class04 */Json_decode.field("class04", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* class05 */Json_decode.field("class05", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* class06 */Json_decode.field("class06", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json)
        ];
}

var Decode = /* module */[/* classes */classes];

function renderStudents(students) {
  return $$Array.map((function (name) {
                return React.createElement("div", undefined, name, React.createElement("a", {
                                className: "print",
                                href: "/print?name=" + name
                              }, "Print"));
              }), students);
}

var component = ReasonReact.statelessComponent("App");

function make(students, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Nametags"), React.createElement("h2", undefined, "Class 04"), React.createElement("div", undefined, renderStudents(students[/* class04 */0])), React.createElement("h2", undefined, "Class 05"), React.createElement("div", undefined, renderStudents(students[/* class05 */1])), React.createElement("h2", undefined, "Class 06"), React.createElement("div", undefined, renderStudents(students[/* class06 */2])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

function output() {
  var students = classes(Json.parseOrRaise(Students));
  return Server.renderToString(ReasonReact.element(undefined, undefined, make(students, /* array */[])));
}

exports.Decode = Decode;
exports.renderStudents = renderStudents;
exports.component = component;
exports.make = make;
exports.output = output;
/* component Not a pure module */
